### ISSUE TITLE
Quality output

### ISSUE THREAD

**Issue by frodrigo** [tyndare/blur-persons#1]
Can we use the same quality as the input image, not 100?
```python
save_and_copy_exif(new_image, filename, new_filename, quality=100)
```

**Comment by tyndare** [comment]
I don't know how to get the quality of input JPEG file.
https://photo.stackexchange.com/questions/88167/is-it-possible-to-find-out-what-compression-ratio-was-used-for-a-particular-jpeg
quality=100 was probably a bad choice, I'll add an option to set it.
