### ISSUE TITLE
Code simplificatino for 360°?

### ISSUE THREAD

**Issue by frodrigo** [tyndare/blur-persons#10]
Why consider the other side of the images of 360, and not doing the same job as regular images? In all case you cut the image in some place.

**Comment by tyndare** [comment]
The script cut images in regions that overlap each others. The overlap try to avoid the situation where a person cut in two regions is not recognized, typically in one side of the cut, the smallest one, but is recognized on the other side of the cut.
  
360 images use a cylindrical projection. The left end side of the image is connected to the right end side, so the script consider that for 360 images the right end side will overlap with the beginning of the image on the left.

Doing the same for non 360 images would make code simpler but be less optimal as this would increase the area to be analyzed for no reason.

**Comment by frodrigo** [comment]
Ok. I miss the point about overlap in general case.

**Comment by frodrigo** [comment]
My goal was just to find a way to factorize code for making the conversion tool of my PR #11.

**Comment by tyndare** [comment]
I know my function code to split region is not clear enough and probably too complex but that's the only working version I was able to write that day.
