### ISSUE TITLE
Fill with color in place of blur

### ISSUE THREAD

**Issue by frodrigo** [tyndare/blur-persons#3]
Maybe we can fill with flat color in place of blur to save save on disk.
Not tested, no idea if the possible saved space.

**Comment by frodrigo** [comment]
* Blur 1pixel : 1256993
* Blur 30pixels: 1137932 -9.4%
* Blur 900pixels: 1126524 -10.8%

![2014-07-31T18:58:39 000Z_2014-07-31T22:39:06 564Z_0006-blurred_](https://user-images.githubusercontent.com/1785486/86173942-0e82f600-bb21-11ea-8245-41994b98d505.jpg)

**Comment by tyndare** [comment]
You can now use option -b color if you want a flat color, as -b grey
https://github.com/tyndare/blur-persons/commit/75557eec9b3d7c636304e0d512acf9f81ad525d4

**Comment by frodrigo** [comment]
Thank
