### ISSUE TITLE
Blur more classes

### ISSUE THREAD

**Issue by frodrigo** [tyndare/blur-persons#4]
I want also to blur licence plate, but while car will do the job.
Can we add an option to blur more objects classes?

**Comment by tyndare** [comment]
I added the option -c to add class of item to blur.
You can now launch it with  -c person -c car
https://github.com/tyndare/blur-persons/commit/292de522675328eeeefea5bba3eaf681b79347a0

**Comment by frodrigo** [comment]
Thank!
